### ISSUE TITLE
NodeJS 12.16.1 binary unavailable

### ISSUE THREAD

**Issue by busflix** [zeit/pkg-fetch#85] opened 2020-03-31 14:35 UTC
request to update the release binaries to the latest date. thanks

**Comment by GrahamCampbell** [comment] 2020-04-23 15:22
12.16.2, really.

**Comment by GrahamCampbell** [comment] 2020-04-23 15:22
Duplicate of https://github.com/zeit/pkg-fetch/issues/79. Please close.

**Closed** 2020-04-26 18:37 UTC
